name: Android Instrumentation Tests

on:
  push:
  pull_request:

jobs:
  test:
    name: Run Instrumentation Tests
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17 with Gradle cache
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-version: '34'
          build-tools: '34.0.0'
          cache: 'gradle'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Install dependencies
        run: ./gradlew dependencies

      - name: Install required system images and emulator
        run: |
          sdkmanager --update
          sdkmanager --install 'emulator'
          sdkmanager --install 'system-images;android-34;default;x86_64'

      - name: Run Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          script: ./gradlew connectedDebugAndroidTest
