name: Android Unit Tests

on:
  push:
  pull_request:

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # - name: Grant execute permission for Gradle
      #   run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew test
