name: Android Instrumentation Tests

on:
  push:
  pull_request:

jobs:
  test:
    name: Run Instrumentation Tests
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

#      - name: Set up JDK 17 with Gradle cache
#        uses: actions/setup-java@v4
#        with:
#          distribution: 'temurin'
#          java-version: '17'
#          cache: 'gradle'

#      - name: Set up Android SDK
#        uses: android-actions/setup-android@v2
#        with:
#          sdk-version: '34'
#          build-tools: '34.0.0'
#          cache: 'gradle'
#
#      - name: Clean Android SDK cache
#        run: rm -rf $ANDROID_HOME/.android
#
#      - name: Update Android SDK
#        run: sdkmanager --update
#
#      - name: Grant execute permission for Gradle
#        run: chmod +x gradlew
#
#      - name: Install dependencies
#        run: ./gradlew dependencies
#
#      - name: Install required system images and emulator
#        run: |
#          sdkmanager --install 'emulator'
#          sdkmanager --install 'system-images;android-34;default;x86_64'
#
#      - name: Create and start AVD
#        run: |
#          echo "no" | avdmanager create avd -n Pixel_3_API_34 -k "system-images;android-34;default;x86_64"
#          $ANDROID_HOME/emulator/emulator -avd Pixel_3_API_34 -no-snapshot -no-window -gpu off &
#          timeout 60 sh -c 'while ! adb shell getprop sys.boot_completed | grep -m 1 "1"; do sleep 5; done;'

      - name: Run Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
#          target: google_apis
#          arch: x86_64
          script: ./gradlew connectedCheck
